apiVersion: v1
kind: Service
metadata:
  name: <REPO_NAME>-api-service
spec:
  type: ClusterIP
  selector:
    app: <REPO_NAME>-api
  ports:
    - port: 80
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REPO_NAME>-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <REPO_NAME>-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: <REPO_NAME>-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z <REPO_NAME>-postgres-service 5432; do echo "Waiting for postgres..."; sleep 2; done']
        - name: run-migrations
          image: <IMAGE_NAME>
          imagePullPolicy: Never
          command: ['node', 'dist/db/migrate.js']
          envFrom:
            - secretRef:
                name: <REPO_NAME>-secret
      containers:
        - name: <REPO_NAME>-api
          image: <IMAGE_NAME>
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: <REPO_NAME>-secret
      terminationGracePeriodSeconds: 30
