apiVersion: v1
kind: PersistentVolume
metadata:
  name: <REPO_NAME>-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /Volumes/Main/<REPO_NAME>/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <REPO_NAME>-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
  volumeName: <REPO_NAME>-postgres-pv
---
apiVersion: v1
kind: Service
metadata:
  name: <REPO_NAME>-postgres-service
spec:
  type: ClusterIP
  selector:
    app: <REPO_NAME>-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <REPO_NAME>-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <REPO_NAME>-postgres
  template:
    metadata:
      labels:
        app: <REPO_NAME>-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: <REPO_NAME>-postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: <REPO_NAME>-postgres-pvc
