apiVersion: v1
kind: Service
metadata:
  name: wanshitong-ui-service
spec:
  type: ClusterIP
  selector:
    app: wanshitong-ui
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanshitong-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanshitong-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: wanshitong-ui
    spec:
      containers:
        - name: wanshitong-ui
          image: <IMAGE_NAME>
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      terminationGracePeriodSeconds: 30
