services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: wanshitong_user
      POSTGRES_PASSWORD: nUwZn4XoyoNk02bccij22CYFpLwkxN3n
      POSTGRES_DB: wanshitong
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
