name: CI

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: self-hosted
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g corepack && corepack enable

      - run: corepack install

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm typecheck

      - run: pnpm test
